from django.db import models

# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.

class Cliente(models.Model):
    cd_regiao = models.DecimalField(max_digits=2, decimal_places=0)
    cd_cliente = models.DecimalField(max_digits=8, decimal_places=0)
    no_apelido = models.CharField(max_length=20)
    no_cliente = models.CharField(max_length=45, blank=True, null=True)
    cd_sexo = models.CharField(max_length=1, blank=True, null=True)
    cd_est_civil = models.CharField(max_length=1, blank=True, null=True)
    dt_nascimento = models.DateField(blank=True, null=True)
    no_profissao = models.CharField(max_length=20, blank=True, null=True)
    no_cid_natural = models.CharField(max_length=20, blank=True, null=True)
    cd_uf_natural = models.CharField(max_length=2, blank=True, null=True)
    no_funcao = models.CharField(max_length=15, blank=True, null=True)
    no_endereco = models.CharField(max_length=45, blank=True, null=True)
    no_bairro = models.CharField(max_length=20, blank=True, null=True)
    no_cidade = models.CharField(max_length=35, blank=True, null=True)
    uf_residencia = models.CharField(max_length=2, blank=True, null=True)
    no_ponto_refer = models.CharField(max_length=50, blank=True, null=True)
    ao_resid_tipo = models.CharField(max_length=1, blank=True, null=True)
    ao_resid_tempo = models.CharField(max_length=10, blank=True, null=True)
    vl_aluguel = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    vl_salario = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    cd_loja_origem = models.CharField(max_length=3, blank=True, null=True)
    cd_representante = models.DecimalField(max_digits=2, decimal_places=0, blank=True, null=True)
    dt_admissao = models.DateField(blank=True, null=True)
    nr_cep_residencia = models.CharField(max_length=10, blank=True, null=True)
    tt_azul = models.SmallIntegerField(blank=True, null=True)
    tt_verde = models.SmallIntegerField(blank=True, null=True)
    tt_vermelho = models.SmallIntegerField(blank=True, null=True)
    tp_cliente = models.CharField(max_length=2, blank=True, null=True)
    nr_fone_amigo = models.CharField(max_length=12, blank=True, null=True)
    no_firma = models.CharField(max_length=45, blank=True, null=True)
    no_endereco_fir = models.CharField(max_length=45, blank=True, null=True)
    no_bairro_fir = models.CharField(max_length=20, blank=True, null=True)
    no_cidade_fir = models.CharField(max_length=20, blank=True, null=True)
    uf_fir = models.CharField(max_length=2, blank=True, null=True)
    nr_fone_fir = models.CharField(max_length=12, blank=True, null=True)
    no_pai = models.CharField(max_length=40, blank=True, null=True)
    no_mae = models.CharField(max_length=40, blank=True, null=True)
    nr_fone_cliente = models.CharField(max_length=12, blank=True, null=True)
    dt_cadastramento = models.DateField(blank=True, null=True)
    fl_situacao = models.CharField(max_length=1, blank=True, null=True)
    ao_sit_atu_cen = models.CharField(max_length=1, blank=True, null=True)
    cd_area_entrega = models.CharField(max_length=4, blank=True, null=True)
    cd_area_cobranca = models.CharField(max_length=4, blank=True, null=True)
    cd_empresa_fun = models.CharField(max_length=2, blank=True, null=True)
    sg_filial_fun = models.CharField(max_length=3, blank=True, null=True)
    fl_mala_direta = models.CharField(max_length=1, blank=True, null=True)
    fl_alterado = models.CharField(max_length=1, blank=True, null=True)
    qt_tempo_serv = models.SmallIntegerField(blank=True, null=True)
    nr_identidade = models.CharField(max_length=12, blank=True, null=True)
    sg_loja = models.CharField(max_length=3, blank=True, null=True)
    fl_conceito = models.CharField(max_length=3, blank=True, null=True)
    cp_cp = models.CharField(max_length=3, blank=True, null=True)
    cd_matricula = models.DecimalField(max_digits=7, decimal_places=0, blank=True, null=True)
    dt_cep = models.DateField(blank=True, null=True)
    cd_cidade = models.CharField(max_length=6, blank=True, null=True)
    nr_ramal = models.CharField(max_length=4, blank=True, null=True)
    cd_pesquisa = models.CharField(max_length=3, blank=True, null=True)
    cd_vendedor = models.DecimalField(max_digits=6, decimal_places=0, blank=True, null=True)
    fl_clipar = models.CharField(max_length=1, blank=True, null=True)
    no_emissor = models.CharField(max_length=10, blank=True, null=True)
    cd_uf_ident = models.CharField(max_length=2, blank=True, null=True)
    cd_bairro = models.CharField(max_length=6, blank=True, null=True)
    cd_bairro_fir = models.CharField(max_length=6, blank=True, null=True)
    cd_cid_natural = models.CharField(max_length=6, blank=True, null=True)
    cd_cidade_fir = models.CharField(max_length=6, blank=True, null=True)
    no_logradouro = models.CharField(max_length=30, blank=True, null=True)
    cd_rua = models.DecimalField(max_digits=6, decimal_places=0, blank=True, null=True)
    cd_avalista = models.DecimalField(max_digits=8, decimal_places=0, blank=True, null=True)
    cd_setor = models.CharField(max_length=4, blank=True, null=True)
    cd_lote = models.CharField(max_length=4, blank=True, null=True)
    no_compend = models.CharField(max_length=90, blank=True, null=True)
    tt_canc = models.SmallIntegerField(blank=True, null=True)
    tt_exc = models.SmallIntegerField(blank=True, null=True)
    tt_av = models.SmallIntegerField(blank=True, null=True)
    fl_conceito1 = models.CharField(max_length=3, blank=True, null=True)
    cd_chave = models.CharField(primary_key=True, max_length=10)
    cd_nomcod = models.CharField(max_length=53, blank=True, null=True)
    no_chvend = models.CharField(max_length=127, blank=True, null=True)
    no_endvirnr = models.CharField(max_length=9, blank=True, null=True)
    no_endvirbl = models.CharField(max_length=7, blank=True, null=True)
    no_endvirap = models.CharField(max_length=9, blank=True, null=True)
    no_endvir = models.CharField(max_length=88, blank=True, null=True)
    no_endvirst = models.CharField(max_length=8, blank=True, null=True)
    no_endvirlt = models.CharField(max_length=8, blank=True, null=True)
    no_endvir1 = models.CharField(max_length=90, blank=True, null=True)
    id_origin = models.CharField(max_length=3, blank=True, null=True)
    id_remote = models.CharField(max_length=3, blank=True, null=True)
    dth_criacao = models.DateTimeField()
    dth_atualizacao = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'cliente'